name: iOS starter workflow

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build Project
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      
    - name: Set Gems
      run: |
        gem install bundler
        bundle install
      
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 13.2.1
        
    - name: Build
      run: |
        set -o pipefail
        xcodebuild build \
        -scheme NotesApp \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
        -derivedDataPath build \
        | xcpretty
        
    - name: Archive derived data artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
        
  test:
    name: Test Project
    needs: build
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set Gems
      run: |
        gem install bundler
        bundle install
        
    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 13.2.1

    - name: Download derived data artifact
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Test
      run: |
        set -o pipefail
        xcodebuild test-without-building \
        -scheme NotesApp \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
        -derivedDataPath build \
        | xcpretty
