name: iOS starter workflow

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  hello:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: echo Hello World
